export const constantStrings = {
  HOME: 'Home',
  LISTING: 'Listing',
  SETTINGS: 'Settings',
  DEVICE_INFO: 'Device Information',
  OS: 'OS',
  OS_VERSION: 'OS Version',
  DEVICE_ID: 'Device ID',
  DEVICE_MODEL: 'Device Model',
  DEVICE_BRAND: 'Device Brand',
  DEVICE_NAME: 'Device Name',
  APP_VERSION: 'App Version',
  FAILED_TO_LOAD: 'Failed to load device info.',
  RETRY: 'Retry',
  PHOTOS: 'Photos',
  PHOTO_ACCESS_DISABLED:
    'Photo access is disabled. Please enable photo permission from Settings.',
  OPEN_SETTINGS: 'Open Settings',
  PHOTO_PERMISSION_REQUIRED: 'Photo permission is required to select a photo.',
  TRY_AGAIN: 'Try Again',
  SELECT_PHOTO: 'Select Photo',
  NO_PHOTO: 'No photo selected',
  CANCEL: 'Cancel',
  PHOTO_ACCESS_DISABLED_TITLE: 'Photo Access Disabled',
  PERMISSION_REQUIRED_TITLE: 'Permission Required',
  NO_DATA_AVAILABLE: 'No data available',
  FETCHING: 'Fetching...',
  NAME_REQUIRED: 'Name is required',
  INVALID_EMAIL: 'Please enter valid email address',
  EMAIL_REQUIRED: 'Email is required',
  BIRTHDATE_REQUIRED: 'Birthdate is required',
  COUNTRY_REQUIRED: 'Country is required',
  SUCCESS: 'Success',
  SETTINGS_SAVED: 'Settings saved successfully!',
  NAME: 'Name',
  ENTER_NAME: 'Enter your name',
  EMAIL_ADDRESS: 'Email Address',
  ENTER_EMAIL: 'Enter your email',
  BIRTHDATE: 'Birthdate',
  COUNTRY: 'Country',
  SAVE: 'Save',
  SELECT_COUNTRY: 'Select Country',
};
